default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devPortfolio_development

test:
  <<: *default
  database: devPortfolio_test


production:
  <<: *default
  database: devPortfolio_production
  username: devPortfolio
  password: <%= ENV['DEVPORTFOLIO_DATABASE_PASSWORD'] %>
